name: Build exe with Pyinstaller

on:
  workflow_dispatch:
    tags:
      - '*.*.*'
    inputs:
      tags:
        required: false
        description: "test build tags"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get tag
      id: tag
      run: |
        echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: my-app-${{ steps.tag.outputs.tag }}
        path: dist/windows
